// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           34
// Async Callback:                       1
// Total number of exported functions:  36

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nft_minter
    (
        setMaxNftsPerTransaction
        setUpdateAttributesRole
        isManaged
        attributeSpecFileName
        getMaxNftsPerTransaction
        getRegisterdCollectionHashes
        getRegisteredBrands
        getNftTokenIdForBrand
        getPriceForTier
        getTagsForBrand
        getMintWhitelist
        addUserToAdminList
        removeUserFromAdminList
        setUniqueFilename
        issueTokenForBrand
        addToWhitelist
        removeFromWhitelist
        setMintWhitelistExpireTimestamp
        buyRandomNft
        buyRandomNftDelegated
        giveawayNfts
        getNftTiersForBrand
        nftIdOffsetForTier
        setRoyaltiesClaimAddress
        setMintPaymentsClaimAddress
        claimRoyalties
        claimMintPayments
        getRoyaltiesClaimAddress
        getMintPaymentsClaimAddress
        getAccumulatedRoyalties
        getAccumulatedMintPayments
        claimRoyaltiesFromMarketplace
        getBrandInfo
        getAllBrandsInfo
        callBack
    )
}
